### ISSUE TITLE
Filter method

### ISSUE THREAD

**Issue by mgesmundo** [ExodusMovement/schemasafe#126]
Awesome work!
There is some method to filtering away properties not in the schema, like the is-my-json-valid filter method does?
Thank you

**Comment by ChALkeR** [comment]
@mgesmundo There is a `removeAdditional` option, but it removes only properties/items blocked with `additionalProperties: false` and `additionalItems: false`, so those should idally be specified everywhere. To check that those are specified everywhere, one can use `allowUnusedKeywords: false` option.

Documentation is still [in progress](https://github.com/ExodusMovement/schemasafe/issues/57), but here is an example:
```js
const { validator, parser } = require('.')

const schema = {
  $schema: 'http://json-schema.org/draft-07/schema#',
  type: 'object',
  required: [],
  properties: {
    x: {
      type: 'integer'
    }
  },
  additionalProperties: false
}
const validate = validator(schema, { removeAdditional: true, requireValidation: true })
const data = { x: 2, foo: 20 }
console.log(validate(data), data) // true, { x: 2 }

const parse = parser(schema, { removeAdditional: true })
console.log(parse('{"x":20, "bar": "string"}')) // { valid: true, value: { x: 20 } }
```

Also, `removeAdditional` will refuse to compile schemas with paths of uncertainty (e.g. `if/then/else`, or `oneOf` without a `discriminator`).

I believe that `filter` implementation in imjv in unsafe, and most of this structure is needed to

**Comment by mgesmundo** [comment]
Thank you @ChALkeR! Super fast answer: great!
I agree your thoughts about the security of `filter` implementation on edge cases.
All the best.

**Comment by ChALkeR** [comment]
Ah, one more difference: imjv will report a validation failure in case if it filtered away anything.
This library will report success if the _modified_ object (i.e. with additional properties removed) passes the validation.

**Comment by ChALkeR** [comment]
@mgesmundo One more note: proper uncertainty checks mentioned above were introduced in `v1.0.0-beta.5` which I just published.
