### ISSUE TITLE
Question about validation

### ISSUE THREAD

**Issue by Zaseth** [ExodusMovement/schemasafe#127]
I'm validating an object that includes a property called 'host'. The host property is an ip address. Is it possible that I can validate this property to be a valid ipv4? This can be done using net.isIPv4, but is it possible to do this in the JSON validator itself?

**Comment by ChALkeR** [comment]
I'm not entirely sure that I understand the question, but JSON Schema has `ipv4` format as mentioned here: https://json-schema.org/understanding-json-schema/reference/string.html

Perhaps that would help?

**Comment by Zaseth** [comment]
Ah yes my bad! That's exactly what I needed, thanks.
