### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Zaseth** [ExodusMovement/schemasafe#130]
Will there be any support for using this library in Typescript?

**Comment by ChALkeR** [comment]
@Zaseth If you mean a simple `.d.ts` for the API -- that's not a priority, but PRs are welcome.
I'll list all options on a single page before 1.0.0 release.

If you mean a typescript definition strictly describing all possible json schemas -- that should probably be placed in a separate repo/project. Is there something for that already? I don't want to make in dependency here though, but that could be done via an easy wrapper.

If you mean something else -- could you elaborate, please?

**Comment by Zaseth** [comment]
Yeah I meant the .d.ts file so we can use this amazing project in Typescript. Once I have the time, I'll most likely create a PR, but it won't be anytime soon. Feel free to close this issue.

**Comment by ChALkeR** [comment]
@Zaseth No, this is a perfectly valid issue, let's keep this open.
I'm looking forward to introducing basic `*.d.ts` typings here, it's just not a priority now.

**Comment by goloroden** [comment]
Hey @ChALkeR 👋 

I have written some basic types, and I would like to submit a PR. However, they are rather basic, i.e. they just support what I needed so far, and it's far from complete.

Is this of interest anyway?

**Comment by goloroden** [comment]
I just decided to add the PR, see #136 for details.

Is there a chance that it can be merged, albeit it's still missing many details?

**Comment by ChALkeR** [comment]
@goloroden Thanks! I updated that to the actual options set and merged. Sorry for not replying earlier.

Note that `formats` and `schemas` are listed with type `any`, that probably needs fixing.
I'm not closing this issue yet.

**Comment by ChALkeR** [comment]
Docs on [Options](https://github.com/ExodusMovement/schemasafe/blob/master/doc/Options.md) just landed, those should be helpful for improving the types specification.

**Comment by ChALkeR** [comment]
I added more type information to [index.d.ts](https://github.com/ExodusMovement/schemasafe/blob/master/index.d.ts), should be a part of 1.0.0 release.

Do those look good?

No typings for schema objects themselves yet though.

**Comment by ChALkeR** [comment]
I added experimental typings for Schema objects. Not tested well enough yet.

**Comment by Zaseth** [comment]
I'm glad that this is being pursued, good job!
