### ISSUE TITLE
Question Regarding Required

### ISSUE THREAD

**Issue by stetsmando** [ExodusMovement/schemasafe#132]
I wanted to see if anyone can point me in the right direction with an issue I'm having.
I'm sure this comes from my lack of understanding but is there a way to have validation fail if things are provided that are not part of the `required` key?

For example, I have a schema that looks like this:
```javascript
const schema = {
  type: 'object',
  required: ['someProp'],
  properties: {
    someProp: {
      type: 'boolean'
    }
  }
}
```

Using that schema, if I validate the below object I would expect it to fail. This is not the case, is there a way to achieve that?
```javascript
const myObj = {
  "another": true,
  "someProp": true
}
``` 

Thanks in advance for any help.

**Comment by ChALkeR** [comment]
I recommend http://json-schema.org/ Slack ([link](https://join.slack.com/t/json-schema/shared_invite/enQtNjc5NTk0MzkzODg5LTVlZGIxNmVhMGY2MWFlYTdiNDQ5NWFiZGUwOThhNmYxZDE0YzA5YjRiOTA5MGY4ZTZlZGZhZDFmYTY4NWM2N2Y)) for general questions about JSON Schema itself.

Also, you are likely looking for [`additionalProperties: false`](https://json-schema.org/understanding-json-schema/reference/object.html#properties) or `unevaluatedProperties: false`.

Note that it should be specified on every object, as JSON Schema is open by default (i.e. anything passes).

`schemasafe` has a `requireValidation: true` option (which is not a part of the schema itself and has to be specified in options), the effect of it is that it refuses to use schemas that can allow unvalidated properties. I.e. it enforces the usage of `additionalProperties` or `unevaluatedProperties` and makes sure that it's not missed in any object.

I'm going to close this question as answered, as it's not an issue.
