### ISSUE TITLE
I need help regarding validation

### ISSUE THREAD

**Issue by Zaseth** [ExodusMovement/schemasafe#133]
Hello.

I've been trying and trying for hours on getting a working json schema for the following data:

```json
{
  "action": "player:action",
  "params": ["snowball", { "x": 1, "y": 2 }]
}

{
  "action": "player:action",
  "params": ["frame", { "frame": "this_is_a_frame" }]
}
```

The above data is **correct**, anything else should be neglected. Sadly, I can't get this to work. How can I do this?

**Comment by ChALkeR** [comment]
I recommend http://json-schema.org/ Slack ([link](https://join.slack.com/t/json-schema/shared_invite/enQtNjc5NTk0MzkzODg5LTVlZGIxNmVhMGY2MWFlYTdiNDQ5NWFiZGUwOThhNmYxZDE0YzA5YjRiOTA5MGY4ZTZlZGZhZDFmYTY4NWM2N2Y)) for general questions about JSON Schema itself.

This issue tracker is for issues specific to `schemasafe` only.

Also, I can't answer this specific question, as it's unclear what is meant by "anything else". E.g. would changing `"x": 1` to `"x": 2` pass?
If you truly need exact match with one of those two objects, e.g. `{ "enum": [ obj1, obj2 ] }` would do, but it's probably not what you meant.

I'm going to close this as a non-issue question, and I recommend asking in the above-mentioned Slack.
