### ISSUE TITLE
How to use the extra formats?

### ISSUE THREAD

**Issue by goloroden** [ExodusMovement/schemasafe#135]
Apparently, schemasafe has [support for the `alphanumeric` format](https://github.com/ExodusMovement/schemasafe/blob/41f209a0141b7d4641807e7058ab7be833eb6281/src/formats.js#L104). However, if I use it within a schema, my application crashes with the following exception being thrown:

> Error: Unrecognized format used: "alphanumeric" at #/properties/contextIdentifier/properties/name

Now what caught my eye in the source code is that `alphanumeric` is a so-called `extra` format. What does that mean? Do I have to enable it somehow, to make it work, or …?

Am I missing something here?

**Comment by goloroden** [comment]
I've figured it out, you have to provide `extraFormats: true` as part of the options object, then it works.

**Comment by ChALkeR** [comment]
Yeah, this is in rc state mostly due to documentation being in progress.
Documentation on options just landed: [Options.md](https://github.com/ExodusMovement/schemasafe/blob/master/doc/Options.md).
