### ISSUE TITLE
Missing build in format for schema draft-07

### ISSUE THREAD

**Issue by GerryFerdinandus** [ExodusMovement/schemasafe#145]
[build in format in schema](https://json-schema.org/understanding-json-schema/reference/string.html#built-in-formats)
- "idn-email"
- "idn-hostname"
- "iri"
- "iri-reference"

Maybe this is already mention somewhere in the documentation. But I can not find it.

**Comment by GerryFerdinandus** [comment]
Close the issue. I don't need it any more.

**Comment by ChALkeR** [comment]
#121
