### ISSUE TITLE
feat: allow regexp for the pattern

### ISSUE THREAD

**Issue by RodrigoEspinosa** [ExodusMovement/schemasafe#147]
## Summary 

The `patter` attribute needs to be a `string`. However, some editors (like in a brand new VSCode) will automatically detect "unnecessary" scapes in strings and remove them, making it harder to send those as strings. 

For instance, this `^[:alnum:]+\@[:alnum:\.]\:(\/[:alnum:]+)*$` will be saved as `^[:alnum:]+@[:alnum:.]:(/[:alnum:]+)*$` automatically. 

As a workaround, we can do something like `/^[:alnum:]+\@[:alnum:\.]\:(\/[:alnum:]+)*$/.toString()` and then remove the first and last `/`, but it would be nice if we can send the regular expression from the beginning. 

https://github.com/ExodusMovement/schemasafe/blob/3f4dc5f9f8e92fca105d140296cb1c13eb17df0d/src/compile.js#L481

**Comment by RodrigoEspinosa** [comment]
I just found that this technique is already being used by some projects like in [shares-server/src/schemas/uuid.js](https://github.com/ExodusMovement/shares-server/blob/master/src/schemas/uuid.js#L7): 


```js
const { UUID_REGEX } = require('../constants')

module.exports = {
  type: 'string',
  maxLength: 36,
  minLength: 36,
  pattern: UUID_REGEX.toString().slice(1, -1),
}
```

**Comment by ChALkeR** [comment]
I don't understand.

What is wrong with `^[:alnum:]+@[:alnum:.]:(/[:alnum:]+)*$`?

Additional escaping is needed for `/` in literal regexps only.
I.e.:
```js
> /a\/b/.source === new RegExp('a/b').source
true
```

Could you share an example that has behavior (i.e. validation) differences?
```

**Comment by ChALkeR** [comment]
If `.` is supposed to be a dot (and not any char), `^[:alnum:]+@[:alnum:\.]:(/[:alnum:]+)*$` should be encoded as `"^[:alnum:]+@[:alnum:\\.]:(/[:alnum:]+)*$"` as a string, for example.

**Comment by RodrigoEspinosa** [comment]
Thanks for the clarification, @ChALkeR!
