### ISSUE TITLE
support for "example" keyword

### ISSUE THREAD

**Issue by larkob** [ExodusMovement/schemasafe#152]
I noticed that the "example" keyword (OpenAPI specification) is not supported, only "examples" for the array type. Could you please consider making the following changes:

1) add 'example' to knownKeywords list in known-keywords.js
```
...['title', 'description', 'deprecated', 'readOnly', 'writeOnly', 'example', 'examples', '$comment'], // unused meta
```

2) add multi-type handle in compile.js (next to the existing one for "examples"):

```
handle('example', ['string', 'finite', 'boolean', 'object'], null) // unused, meta-only
handle('examples', ['array'], null) // unused, meta-only
```

**Comment by ChALkeR** [comment]
Sorry for the late response.

Yes, it's indeed defined in OpenAPI.

Adding to the next release.
