### ISSUE TITLE
Add yourself to JSON Schema implementations page

### ISSUE THREAD

**Issue by gregsdennis** [ExodusMovement/schemasafe#157]
Hey there!  Nice implementation!  Glad to see you support 2020-12!

Please consider submitting a PR to add yourself to the [JSON Schema implementations page](https://json-schema.org/implementations.html).  ([Example PR](https://github.com/json-schema-org/json-schema-org.github.io/pull/503))

**Comment by ChALkeR** [comment]
Just landed https://github.com/ExodusMovement/schemasafe/commit/b772e9d2c68347516e15cab07372ead5b65d85da which should help with that.

**Comment by ChALkeR** [comment]
PR: https://github.com/json-schema-org/json-schema-org.github.io/pull/535
