### ISSUE TITLE
Build time throw for Github Workflow schema

### ISSUE THREAD

**Issue by Aplietexe** [ExodusMovement/schemasafe#158]
When trying to use the [GitHub Workflow schema](https://json.schemastore.org/github-workflow.json) from schemastore, an error is thrown at build time:

```
Error: Unprocessed keywords: ["properties"] at #/properties/on/oneOf/2/properties/branch_protection_rule
```

Perhaps it is because `"properties"` is present although `branch_protection_rule` is either an object or null. In any case, that is fine according to the metaschema, and seems to be a common practice to reduce duplication. 

Example:

```js
import { validator } from '@exodus/schemasafe'
// https://json.schemastore.org/github-workflow.json
import schema from './schema.js'

validator(schema)
```

`schema.js` simply `export default`s the schema from the link.

**Comment by ChALkeR** [comment]
The proper fix is to update the schema version to `"$schema": "https://json-schema.org/draft/2019-09/schema"` or later, otherwise any compliant validator MUST ignore the sibling `property` keywords and those don't actually validate anything. Schemasafe just makes that mistake visible by default.

**Comment by ChALkeR** [comment]
@Aplietexe I reported this bug here: https://github.com/SchemaStore/schemastore/issues/3102

**Comment by ChALkeR** [comment]
Closing as answered, this is a problem with schemastore schemas being incorrect (though technically valid, but not doing what they are intended to do).

**Comment by ChALkeR** [comment]
A separate [linter mode](https://github.com/ExodusMovement/schemasafe/blob/master/doc/Linter.md) is introduced in 1.1.0/1.1.1
