### ISSUE TITLE
`opts.includeErrors` does nothing in default case for `validator()`

### ISSUE THREAD

**Issue by jason-curtis** [ExodusMovement/schemasafe#168]
According to the [README](https://github.com/ExodusMovement/schemasafe#enabling-errors-shows-information-about-the-source-of-the-error), this should create a validator that returns errors:
`const validate = validator(schema, { includeErrors: true })`

Instead, that validator only returns `true` or `false`.

Failing Jest test case:

```typescript
import { validator, ParseResult } from '@exodus/schemasafe';

describe('validate', () => {
    it('validates with errors', () => {
        const schema = {
            type: 'object',
            required: ['hello'],
            properties: {
                hello: {
                    type: 'string'
                }
            }
        }
        const validate = validator(schema, { includeErrors: true })
        expect(validate({ hello: 100 })).toEqual({ valid: true, errors: [{ keywordLocation: '#/properties/hello/type', instanceLocation: '#/hello' }] })
    })
});
```

error returned:

```bash
    expect(received).toEqual(expected) // deep equality

    Expected: {"errors": [{"instanceLocation": "#/hello", "keywordLocation": "#/properties/hello/type"}], "valid": true}
    Received: false
```

**Comment by ChALkeR** [comment]
The example at the linked section of the [README](https://github.com/ExodusMovement/schemasafe#enabling-errors-shows-information-about-the-source-of-the-error) works.

Validator mode outputs errors on a separate property, not via returning them, to ensure that a simple `if (validate(x))` mistake is never made by the consumer.

See [Error handling](https://github.com/ExodusMovement/schemasafe/blob/master/doc/Error-handling.md) for more documentation.
